goldmark:
  renderer:
    unsafe: true
  parser:
    attribute:
      block: true
    wrapStandAloneImageWithinParagraph: false
highlight:
  noClasses: false
  tabWidth: 2
tableOfContents:
  endLevel: 2
  ordered: false
