hugoVersion:
  extended: true
  min: 0.123.8
imports:
  - path: anadea
mounts:
  - source: assets
    target: assets
  - source: node_modules/@builder.io/partytown/lib/partytown.js
    target: assets/js/partytown.js
  - source: static
    target: static
  - source: node_modules/@builder.io/partytown/lib
    target: static/~partytown
    excludeFiles: debug
