includeNewer: true
indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: true
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 100
    name: date
    pattern: ""
    toLower: true
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 100
    name: categories
    pattern: ""
    toLower: true
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 100
    name: industries
    pattern: ""
    toLower: true
    type: basic
    weight: 100
threshold: 100
toLower: true
