networks:
  anadea:
    name: blog

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    restart: unless-stopped
    ports:
      - 1313:1313/tcp
      - 8081:8081/tcp
    volumes:
      - $PWD:/app
    networks:
      - anadea
