local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "img"

publish_mode: simple

collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Publish Date", name: "publishDate", widget: "datetime", default: ""}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Og Image", name: "og_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Short Description", name: "description", widget: "text"}

      - label: "Questionary"
        name: "questionary"
        widget: "list"
        fields:
          - {label: Question, name: question, widget: string, required: false}
          - {label: Answer, name: answer, widget: string, required: false}

      - label: "Promote post"
        name: "promote"
        widget: "object"
        fields:
          - {label: "Promote", name: "promote", widget: "boolean", required: false, default: false}
          - {label: "Promote Url", name: "promote_url", widget: "string", required: false}

      - {label: "Top", name: "top", widget: "boolean", required: false, default: false}

      - label: Authors
        name: authors
        widget: relation
        collection: "authors"
        required: false
        multiple: true
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "name"

      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "categories"
        required: false
        multiple: true
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "name"

      - label: "Industries"
        name: "industries"
        widget: "relation"
        collection: "industries"
        required: false
        multiple: true
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "name"
    sortableFields: ["title", "publishDate"]

  - label: "Authors"
    label_singular: "Author"
    identifier_field: name
    name: "authors"
    folder: "data/authors"
    path: "{{slug}}"
    extension: 'json'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Team", name: "team", widget: "boolean", default: false}
      - {label: "Member Since", name: "memberSince", widget: "datetime"}
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        default: '/img/default-avatar-icon.svg'
        media_folder: "/assets/img/avatars"
        public_folder: "/img/avatars"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Short Description", name: "shortDescription", widget: "text"}
      - {label: "Position", name: "position", widget: "string", required: false}
    sortableFields: ["name", "memberSince"]

  - label: "Sales"
    label_singular: "Sale"
    identifier_field: name
    name: "sales"
    folder: "data/sales"
    path: "{{slug}}"
    extension: 'json'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - label: "Avatar"
        name: "avatar"
        widget: "image"
        required: false
        default: '/img/default-avatar-icon.svg'
        media_folder: "/assets/img/avatars"
        public_folder: "/img/avatars"
      - {label: "Link", name: "link", widget: "string", }

  - label: "Categories"
    label_singular: "Category"
    identifier_field: name
    name: "categories"
    folder: "data/categories"
    path: "{{slug}}"
    extension: 'json'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
    sortableFields: ["name"]

  - label: "Industries"
    label_singular: "Industry"
    identifier_field: name
    name: "industries"
    folder: "data/industries"
    path: "{{slug}}"
    extension: 'json'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - label: Sale
        name: sale
        widget: relation
        collection: "sales"
        default: "Irina Lysenko"
        multiple: false
        search_fields: ["name"]
        display_fields: ["name"]
        value_field: "name"
    sortableFields: ["name"]
